version: "3.7"
services:
  
  webapp:
    build:
      context: .
    environment:
      GUNICORN_CMD_ARGS: "--keyfile=certs/generator-webapp-1.key --certfile=certs/generator-webapp-1.crt"
      PORT: 3004
    restart: unless-stopped
    ports:
      - '3004:3004'

networks:
  default:
    name: hi_default # For proxy.
    external: true
