version: '3.2'

services:

  git-server:
    build: git-server
    restart: unless-stopped

  spring:
    build: spring
    links:
     - mongo
     - sparql
    volumes:
     - type: volume
       source: bundle
       target: /data/bundle
     - type: volume
       source: git
       target: /data/git
     - type: volume
       source: graphviz
       target: /data/graphviz
    environment:
     - SPARQL_ENDPOINT=http://sparql:3030/cwlviewer/
     - SPRING_DATA_MONGODB_HOST=mongo
     - SPRING_DATA_MONGODB_PORT=27017
     - BUNDLESTORAGE=/data/bundle
     - GITSTORAGE=/data/git
     - GRAPHVIZSTORAGE=/data/graphviz
    restart: unless-stopped

  mongo:
    image: mongo:3.4
    volumes:
      - type: volume
        source: mongo
        target: /data/db
    restart: unless-stopped

  sparql:
    image: stain/jena-fuseki:3.4.0
    volumes:
    - type: volume
      source: sparql
      target: /fuseki/databases/cwlviewer
    command: "/jena-fuseki/fuseki-server --loc=/fuseki/databases/cwlviewer /cwlviewer"
    restart: unless-stopped

volumes:
  bundle:
  git:
  graphviz:
  mongo:
  sparql:

networks:
  default:
    external:
      name: hi_default # For proxy.
