version: "3.7"
services:
  
  generator:
    build:
      context: generator
    restart: unless-stopped
    environment:
      PORT: 3004
    ports:
      - '3004:3004'

networks:
  default:
    external:
      name: hi_default # For proxy.
