services:

  proxy:
    build:
      context: proxy
    container_name: phenoflow-proxy-1
    image: phenoflow-proxy-1
    restart: unless-stopped
    command: ["./wait-for-it.sh", "--timeout=0", "webapp:3003", "--", "nginx", "-g", "daemon off;"]
    ports:
      - 3003:80

  gitea:
    image: docker.gitea.com/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://localhost:3003/gitea/
    restart: unless-stopped
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 222:22

volumes:
  gitea_data:

networks:
  default:
    name: hi_default # For proxy.
    external: true