version: "3.7"

services:
  webapp-test:
    build:
     context: web
     dockerfile: Dockerfile.test
    environment:
      DEFAULT_PASSWORD: ${DEFAULT_PASSWORD}
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      RSA_PRIVATE_KEY: ${RSA_PRIVATE_KEY}
    volumes:
      - pf_uploads:/home/node/app/uploads
    secrets:
      - rsa-private-key
    command: ["./bin/wait-for-it.sh", "--timeout=0", "phenoflow_mariadb_1:3306", "--", "npx", "mocha", "-g", "CI1|CI3|t2dm|covid", "--exit"]

volumes:
  pf_uploads:

networks:
  default:
    external:
      name: hi_default # For proxy.

secrets:
  rsa-private-key:
    file: ${HOST_RSA_PRIVATE_KEY_PATH}${RSA_PRIVATE_KEY}
