version: "3.7"
services:
  
  generator:
    build:
      context: .
    restart: unless-stopped
    environment:
      PORT: 3004

networks:
  default:
    name: hi_default # For proxy.
    external: true
      
