# Phenoflow

# cwlviewer

location /phenoflow {
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header X-Forwarded-For $remote_addr;
  proxy_pass https://cwlviewer-spring-1:8443;
}

# importer

location ~ ^/phenoflow/(docs|importer|login) {
  proxy_set_header Host $http_host;
  proxy_set_header X-Real-IP  $remote_addr;
  proxy_set_header X-Forwarded-For $remote_addr;
  proxy_pass https://importer-webapp-1:3003;
}

# gitea

location ~ ^/(gitea|v2)($|/) {
  client_max_body_size 512M;

  # make nginx use unescaped URI, keep "%2F" as-is, remove the "/gitea" sub-path prefix, pass "/v2" as-is.
  rewrite ^ $request_uri;
  rewrite ^/(gitea($|/))?(.*) /$3 break;
  resolver 127.0.0.11 valid=10s;
  proxy_pass http://gitea:3000$uri;

  # other common HTTP headers, see the "Nginx" config section above
  proxy_set_header Connection $http_connection;
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
}