FROM library/postgres
COPY init.sql /docker-entrypoint-initdb.d/0-init.sql
# The be executed manually, after Broadsea tools run their migration.
COPY ohdsi.sql .
# Data model (https://github.com/OHDSI/CommonDataModel/tree/master/PostgreSQL (v6 branch))
ARG ddl="cdm/PostgreSQL/OMOP CDM postgresql ddl.txt"
COPY ${ddl} /docker-entrypoint-initdb.d/1-ddl.sql
# Indexes
ARG pk_indexes="cdm/PostgreSQL/*indexes*.*"
COPY ${pk_indexes} /docker-entrypoint-initdb.d/2-pk-indexes.sql
# Constraints
ARG constraints="cdm/PostgreSQL/*constraints*.*"
COPY ${constraints} /docker-entrypoint-initdb.d/3-constraints.sql
# Results
ARG results="cdm/PostgreSQL/OMOP CDM Results*ddl*.*"
COPY ${results} /docker-entrypoint-initdb.d/4-results.sql
