version: "3.7"

services:
  webapp-test:
    build:
     context: .
     dockerfile: Dockerfile.test
    environment:
      NODE_EXTRA_CA_CERTS: ${NODE_EXTRA_CA_CERTS}
    command: ["npx", "mocha", "-g", "PA1", "--exit"]

networks:
  default:
    name: hi_default # For proxy.
    external: true
